services:
  lms-tg-app-staging:
    image: {{ .image }}
    restart: unless-stopped
    ports:
      - "127.0.0.1:3001:80"  # Другой порт для staging
    environment:
      - NODE_ENV=staging
    networks:
      - lms-staging-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  lms-staging-network:
    driver: bridge
    name: lms-staging-network
