name: Release and Deploy to Server

on:
  push:
    tags: ["v*"]
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to (server)"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - prod

env:
  ENVIRONMENT: ${{ github.event.inputs.environment || 'staging' }}
  DOCKER_IMAGE: ${{ github.repository }}:${{ github.event.inputs.environment || 'staging' }}

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Docker images.
        uses: ScribeMD/docker-cache@0.5.0
        with:
          key: docker-${{ runner.os }}
          
      - name: Build Docker image with docker-compose
        run: |
          docker build -f deploy/Dockerfile -t ${{ env.DOCKER_IMAGE }} .
          docker tag ${{ env.DOCKER_IMAGE }} ${{ env.DOCKER_IMAGE }}-$(date +%Y%m%d-%H%M%S)

      - name: Save Docker image
        run: |
          docker save ${{ env.DOCKER_IMAGE }} | gzip > lms-tg-app.tar.gz

      - name: Upload server deploy artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: |
            lms-tg-app.tar.gz
          retention-days: 2

  deploy-to-server:
    name: Deploy to server
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: ./

      - name: List artifacts
        run: ls -la

      - name: Prepare server directory
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT || 22 }}
          script: |
            mkdir -p /opt/deploy/lms-tg-app
            cd /opt/deploy/lms-tg-app
            docker-compose -f deploy/docker-compose.${{ env.ENVIRONMENT }}.yml down --remove-orphans || true
            docker rmi ${{ env.DOCKER_IMAGE }} || true

      - name: Move docker-compose file
        run: |
          mv deploy/docker-compose.${{ env.ENVIRONMENT }}.yml docker-compose.yml
          rm -rf deploy

      - name: Copy files to server
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT || 22 }}
          source: |
            lms-tg-app.tar.gz,
            docker-compose.yml
          target: "/opt/deploy/lms-tg-app/${{ env.ENVIRONMENT }}/"

      - name: Deploy with docker-compose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT || 22 }}
          script: |
            cd /opt/deploy/lms-tg-app/${{ env.ENVIRONMENT }}
            docker load < lms-tg-app.tar.gz
            docker-compose -f docker-compose.yml up -d
            sleep 15
            docker-compose -f docker-compose.yml ps
            if [ "${{ env.ENVIRONMENT }}" = "staging" ]; then
              curl -f http://localhost:3001/health || echo "Health check failed"
            else
              curl -f http://localhost:3000/health || echo "Health check failed"
            fi
            docker image prune -f
            rm -f lms-tg-app.tar.gz
