name: Test and Lint

on: [push]

jobs:
    test-and-build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"
                  cache-dependency-path: "**/package-lock.json"
            - name: Install spec dependencies

              run: npm ci
              working-directory: spec

            - name: Generate TypeSpec
              run: npx tsp compile . --output-dir ../tsp-output
              working-directory: spec

            - name: Build client library
              run: npm i && npm run build
              working-directory: tsp-output/clients/js

            - name: Install dependencies
              run: npm ci

            - name: Lint
              env:
                  NODE_ENV: production
              run: npm run lint

            - name: Build
              env:
                  NODE_ENV: production
              run: npm run build
